# Generated by Django 5.0.1 on 2024-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_locationimpressions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True},
        ),
    ]
