# Generated by Django 5.0.6 on 2024-11-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
    ]
